src/Two/AbstractProvider.php
src/Two/GoogleProvider.php

Added a configuration option for scope separator and query string encoding type to `AbstractProvider.php`, making it easier to write your own providers without overwriting `formatScopes()` and `buildAuthUrlFromBase()`.

Scope Separator and URL Encoding Type configurable in AbstractProvider

---

src/SocialiteManager.php

While creating some OAuth1 Providers I needed to call formatConfig which was not possible due to the fact that it was set to protected. It should be set to public so that it could be called when a new OAuth1 Provider extends Socialite.
This doesn't work at the moment, when formatConfig is set to public everything works great.
```php
public function boot()
{
$socialite = app()->make('Laravel\Socialite\Contracts\Factory');
$socialite->extend('flickr', function ($app) use ($socialite) {
$config = $app['config']['services.flickr'];
return new FlickrProvider(
$app['request'],
new FlickrServer($socialite->formatConfig($config))
);
});
}
```

Make formatConfig public

---

src/Two/FacebookProvider.php

Prevents 1.0 upgrade warning. Reference: https://developers.facebook.com/docs/apps/versions#dialogs

Include API version in auth url

---

src/Two/AbstractProvider.php

This makes it a bit easier to add any additional parameters needed for building
the auth url in a provider. **For example**, in Facebook you might have the need to send the 
`auth_type` parameter for forcing *rerequests* and *reauthentications*:
```php 
// FacebookProvider
protected function getCodeRequestParameters($state)
{
return array_merge(parent::getCodeRequestParameters($state), ['auth_type' => 'rerequest']);
}
```

Move auth url parameters to own method.

---

src/Two/GithubProvider.php

Same fix as the FB Provider. In Github (at least with new accounts) the email is set to be hidden by default in the user profile and this causes an error since that field won't be available for Socialite's **mapUserToObject** method.
Undefined index error before fix:
Fallback null value for missing email after fix:

Fix for undefined index error when email is hidden

---

src/One/TwitterProvider.php

This pull request fixes an issue where several properties about a Twitter user are discarded, namely any profile background image URLs, as well as the https version of the avatar URL.
The user object coming back from `League\OAuth1\Client\Server\Twitter::userDetails()` separates all the data about a Twitter user's URLs (`profile_background_image_url`, `profile_background_image_url_https`, `profile_image_url`, `profile_image_url_https`, and `profile_banner_url`) into a property called `urls`, instead of the `extra` property that contains all the additional user data. This happens here: https://github.com/thephpleague/oauth1-client/blob/master/src/Client/Server/Twitter.php#L57
The issue stems from this line: https://github.com/laravel/socialite/blob/2.0/src/One/AbstractProvider.php#L65 …

Override of user method in Twitter Provider.

---

src/Two/FacebookProvider.php

When running the callback in a popup, Facebook recommends using ```&display=popup``` in order for the dialog to render properly.

Added support for Facebook popup dialog

---

src/SocialiteManager.php
src/Two/LinkedInProvider.php

This adds a LinkedIn Provider with basis profile + email fields.
Besides the name/email/avatar, some additional raw fields are requested.
This currently doesn't work on the latest Guzzle 6 release, until a release with https://github.com/guzzle/psr7/commit/962735c754f2a562a619b456a3aa4e614f0e5360 is tagged.

Add LinkedIn Provider

---

src/Two/LinkedInProvider.php

Make the fields a bit readable + include the original picture in the profile response.
The regular (small) picture is still used for the default avatar.

Add original picture to LinkedIn

---

src/One/TwitterProvider.php
src/Two/FacebookProvider.php
src/Two/LinkedInProvider.php

This adds an attribute `avatar_original` with the larger images for LinkedIn, Twitter and Facebook.
The normale avatar pictures are pretty small, so if you want to use them for anything else then a tiny thumb, this makes that possible.
LinkedIn: Supplies original image when request
Twitter: Suggests so strip `_normal`: https://dev.twitter.com/overview/general/user-profile-images-and-banners
Facebook: Has a width/height parameter, just supply a large constraint (1920) in this case)
Perhaps other providers have the same possibilities, but not sure. If more support this, we could add a method to the AbstractUser perhaps?

Add original/large avatars

---

src/Two/FacebookProvider.php

It's not guaranteed that the first name and last name are always set on Facebook...
Added checks on first name and last name to make sure the following exception isn't thrown:
```
Undefined index: first_name (Line 97)
.../vendor/laravel/socialite/src/Two/FacebookProvider.php
```

First/last name not always set for Facebook

---

src/Two/LinkedInProvider.php

For some reason, LinkedIn isn't totally reliable without this. It has problems when users login in during the OAuth process. This should fix that.

Send grant_type as POST param

---

src/Two/FacebookProvider.php

Version 2.4 of the Facebook Graph API [was released today](https://developers.facebook.com/docs/apps/changelog/).
This is technically a BC since each version of the Graph API has it's own set of breaking changes. The developer shouldn't rely on a default Graph API version fallback for their requests since each minor upgrade could break their Facebook app.
There should be a way to set the Graph API version via the config so that the developer can manually upgrade the Graph version and test the app before deploying to production.
I was going to submit a PR that would achieve this but since the `AbstractProvider` doesn't seem to allow arbitrary config injection via the constructor, I'm assuming I'd need a special setter method on the `FacebookProvider` for the Graph API version and then have …

Update Facebook Graph API version to v2.4

---

src/Two/FacebookProvider.php

Graph API v2.4 requires a fields parameter to return anything beyond id, name, and avatar. This fix sets the default fields to match the default scope request and common user mapping (first_name, last_name, email). Also allows custom fields to be requested instead via the fields() method.

Adds 'fields' parameter support

---

src/Two/AbstractProvider.php
tests/OAuthTwoTest.php

By doing this we're protecting against people trying to guess the state.

Pull the state from the session

---

src/Two/AbstractProvider.php

This pull request adds the ability to set arbitrary request parameters to the provider redirect response. 
The use case for this feature comes from the many popular OAuth2 providers that support a variety of custom parameters. In particular, I was attempting to use the `hd` parameter (Google documentation [here](https://developers.google.com/identity/protocols/OpenIDConnect?hl=en#hd-param)) that Google OAuth2 allows for, but I did not see a way to utilize that using Socialite.
To use this, it is quite similar to the `scopes` feature:
```php
return $provider
->scopes(['email', 'profile'])
->parameters(['hd' => 'example.com'])
->redirect();
```

Add support for custom request parameters to the redirect response

---

src/Two/FacebookProvider.php

This change makes better secured Server API calls.
There is a Facebook App setting named "Require App Secret".
When this setting is enabled every API call has to include a parameter called "appsecret_proof".
Facebook documentation recommends to enable this settings so that if a user's access token is stolen by a malicious software, every API call without an appsecret_proof will fail.
The app secret proof is a sha256 hash of your access token, using the app secret as the key. Here's what the call looks like in PHP:
```php
$appsecret_proof= hash_hmac('sha256', $access_token, $app_secret); 
```
Facebook Docs
- Verifying Graph API Calls with appsecret_proof: https://developers.facebook.com/docs/graph-api/securing-requests#appsecret_proof
- Login Security: …

Send appsecret_proof on FacebookProvider getUserByToken method.

---

src/Two/LinkedInProvider.php

Same method as is available for the [Facebook Provider](https://github.com/laravel/socialite/blob/2.0/src/Two/FacebookProvider.php#L131-L142), would be useful to allow this with LinkedIn too.

Add the ability to specify which fields to return from the LinkedIn Provider

---

src/Two/GoogleProvider.php

No need to specify anything related to "Google +". Some Google Apps accounts may have it disabled or G+ may not be usefull for an account.
I have checked the given changes for my own use (Google Apps) and they are working as expected (the mapping is correctly done).

Replaced G+ by OpenID in scopes

---

src/Two/GoogleProvider.php

When using Google Sign-in, using G+ is unnecessary and can be blocked with Google Apps.
Google+ can be disabled on Google Apps domains, or when enabled, it forces the user to subscribe to G+.

Replaced G+ scopes by Google Sign

---

src/Two/AbstractProvider.php

Google and Facebook require certain scopes to login correctly so they
don't throw an error, which are included by default. However, when a
user adds their own scopes, it overrides these scopes that they don't
know about. This makes it merge them instead.

Make AbstractProvider::scopes() more intuitive

---

src/One/BitbucketProvider.php
src/SocialiteManager.php
src/Two/BitbucketProvider.php

On July 30, 2015 Bitbucked introduced OAuth2 - [Blog Record](https://blog.bitbucket.org/2015/07/30/bitbucket-now-supports-oauth2-and-fine-grained-scopes-for-resources/).
With OAuth2 you get access to user email and fine-grained scopes.

bitbucket oauth2

---

src/Two/GoogleProvider.php

Without the `openid` scope, the name of the user isn't returned when G+ is disabled (for Google Apps) or the user isn't registered

Added OpenID scope

---

src/One/AbstractProvider.php
src/Two/AbstractProvider.php

These are just tweaks in the DocBlocks, not highly important. 
I got myself confused when I received a "\Symfony\Component\HttpFoundation\RedirectResponse" instead of "\Illuminate\Http\RedirectResponse" from the GoogleProvider::redirect() method. Actually that was right... only the DocBlock was wrong.

Fixed some DocBlocks that had missing sections and wrong types.

---

src/Two/AbstractProvider.php

Use case: when authenticating on a client, and wishing to verify access_token on the server, by passing access_token to server.
Many people have this issue, and it can easily be solved:
http://stackoverflow.com/questions/30543991/laravel-socialite-get-user-details-by-token
http://stackoverflow.com/questions/33088447/how-to-get-facebook-id-using-socialite-laravel-5-using-face-book-token?rq=1

Add ability to get basic social user details from an already known access_token

---

src/Two/FacebookProvider.php

Added method to set auth_type=rerequest for re-requesting permissions which were denied earlier.

Facebook re-request denied permissions.

---

readme.md
src/Two/AbstractProvider.php
src/Two/FacebookProvider.php
src/Two/GoogleProvider.php
src/Two/User.php
tests/OAuthTwoTest.php

Previously the OAuth2 refresh token was inaccessible. This PR exposes it in the User object when it is returned by the provider. I've regression tested this change with each of the supported OAuth2 providers: Google, Facebook, GitHub and LinkedIn.
Note: [Google only includes the refresh_token on the first authorization](http://stackoverflow.com/a/10857806/166339). To force Google to include the refresh_token every time (such as you might do while validating this PR!), you can pass a couple of additional parameters as shown below.
```php
public function redirectToGoogle() {
return Socialite::with('google')
->scopes(['profile', 'email'])
->with(['access_type' => 'offline', 'approval_prompt' => 'force'])
->redirect();
}
```
Note: This is a refactoring of PR #143 based on @taylorotwell's …

Expose OAuth2 refresh_token and expires_in when available (refactored)

---

src/AbstractUser.php

Fix bug introduced in a2eb7a1386db9a152a7d9e2287498d5f461157ea and change the `$user` access for `protected` to `public`.
See https://github.com/laravel/socialite/commit/a2eb7a1386db9a152a7d9e2287498d5f461157ea#commitcomment-17645264

[2.0] Change the scope of $user

---

src/One/AbstractProvider.php
src/Two/AbstractProvider.php

Return the expected `\Illuminate\Session\Store` instead of a `\Illuminate\Session\SessionInterface`
See calls to `get`, `set` and `pull`

Return \Illuminate\Session\Store

---

src/Two/FacebookProvider.php

The app secret proof parameter is now sent only if a Facebook app is
configured.
With the previous revision you can't retrieve the user without having a client secret configured.
The API raises the following error: Invalid appsecret_proof provided in the API argument.

getUserByToken app secret proof fix

---

src/Two/AbstractProvider.php

There may be a scenario when a provider class can be extended and override the scopes (or add additional ones for example in case of GoogleProvider), example:
```php
<?php
use Laravel\Socialite\Two\GoogleProvider;
class YoutubeProvider extends GoogleProvider {
public function getScopes()
{
return array_merge(parent::getScopes(), [
'https://www.googleapis.com/auth/youtube.readonly'
]);
}
}

Use the public method to get the scopes

---

src/Two/AbstractProvider.php

In some scenarios we could override the session state string with another type of encryption. For example an use case will be to store encrypted information into the session state.

Allow overriding the session state string.

---

readme.md

Added a small section to the docs detailing the use of `->stateless()`. This was introduced in #68 but was never documented

Added docs on stateless auth

---

src/One/AbstractProvider.php

The `Two/AbstractProvider.php` has `userFromToken($token)` to retrieve
user profile from a `token`.
While `One/AbstractProvider.php` doesn’t have this feature, I added
`userFromTokenAndSecret($token, $secret)` to retrieve user profile from
the  `token` and `secret`. (Tested with Twitter).

add "get user profile" from `token` and `secret`

---

.travis.yml

Disable php 5.5 in .travis.yml
Problem 1
- illuminate/contracts 5.5.x-dev requires php >=7.0 -> your PHP version (5.5.21) does not satisfy that requirement.
- illuminate/contracts 5.4.x-dev requires php >=5.6.4 -> your PHP version (5.5.21) does not satisfy that requirement.
- Installation request for illuminate/contracts ~5.4 -> satisfiable by illuminate/contracts[5.4.x-dev, 5.5.x-dev].

Update php versions in .travis.yml

---

src/One/AbstractProvider.php
src/Two/AbstractProvider.php

As `put` function is part of `\Illuminate\Session\Store`, not `\Symfony\Component\HttpFoundation\Session\SessionInterface`.

[3.0] Always use session().

---

src/Two/BitbucketProvider.php

As `parseAccessToken` function as been removed in  https://github.com/laravel/socialite/commit/713b4afd3bdc5b07f76975cf584ebcb3a68d96bf.

[3.0] Bitbucket - fix access_token parsing

---

src/Two/AbstractProvider.php

The expected behaviour of `$state` was to use the `getState` method. On branch `2.0` this was already implemented, but on `3.0` something was not right and the method is not used. This fixes this issue which allows the session state to be overwritten if needed.

Make use of getState method

---

src/Two/BitbucketProvider.php

These tokens are necessary for Bitbucket OAuth. Otherwise a `400 Bad Request` (*client id must be provided*) is returned.
I remember these being missing from the 2.0 release as well. Not sure if it's just me, but [Shift](https://laravelshift.com) does not work without them and they seem inline with the other providers.

Send client fields to Bitbucket

---

src/Two/FacebookProvider.php

[Graph v2.9](https://developers.facebook.com/blog/post/2017/04/18/graph-api-v2.9/) is a thing now. :)

Bump Graph API version to v2.9

---

README.md
src/Two/AbstractProvider.php

Ran into an issue where the Stripe provider has a scope set by default ('read_write') which i need to replace with a different scope.
The documentation states that the `scopes` method will overwrite the existing scopes, however it actually just merges the ones supplied with the existing scopes.
I've updated the documentation for `scopes` to state that it merges the supplied scopes with the existing ones, and added a new method `setScopes` to completely overwrite the existing scopes.

Add setScopes method and update documentation

---

src/SocialiteManager.php

As I read in PR #121, there shouldn't be extra dependencies added to the socialite packages. But it become very handy to generate an url automatically by route name in a multi domain / stages setup. So I've added the `value` helper so you can call any "route generation" method within a closure;
```php
'google' => [
'client_id' => env('GOOGLE_CLIENT_ID'),
'client_secret' => env('GOOGLE_CLIENT_SECRET'),
'redirect' => function () {
return route('name_of_the_callback_route');
}
],
```
Hopefully you'll like the idea!

Using the value helper so a closure can be provided

---

src/SocialiteManager.php
src/Two/AbstractProvider.php

This commit will allow to set custom Guzzle options in your services.php file (same as for Sparkpost, Mailgun etc).
```
'facebook' => [
'client_id'     => env('FACEBOOK_CLIENT_ID'),
'client_secret' => env('FACEBOOK_CLIENT_SECRET'),
'redirect'      => env('FACEBOOK_REDIRECT'),
'guzzle'        => [
'expect' => false,
'curl'   => [
CURLOPT_IPRESOLVE => CURL_IPRESOLVE_V4,
],
]
]
```

Allow setting custom Guzzle request options

---

src/One/AbstractProvider.php
src/Two/AbstractProvider.php
tests/OAuthOneTest.php
tests/OAuthTwoTest.php

Illuminate extends Symfony's RedirectResponse with ResponseTrait, which
introduces the `header()` method. By not using Illuminate's
RedirectResponse Socialite breaks middlewares that try to add headers to
every response (e.g. no-cache headers).

Use Illuminate's RedirectResponse instead of Symfony's

---

src/Two/BitbucketProvider.php

In Bitbucket's implementation of OAuth2, the space character is the delimiter for scopes.
When trying to request multiple scopes, the request fails with the callback url having `error_description` appended to it with the value of 'Unknown scope: ', and then a comma-delimited list of scopes.  After that the listed `error` variable has a value of 'invalid_scope'.

Change $scopeSeparator to a space in BitbucketProvider

---

src/SocialiteManager.php

I needed a dynamic way to define the callback url due to all the different environments (domains) my application is deployed at. I was using an env variable for that, but I believe allowing a relative URI is more elegant. It also helps mitigate some of the headaches developers might have when the URL is hardcoded in the config.

Allow the callback url to be relative

---

.travis.yml
composer.json
tests/OAuthOneTest.php
tests/OAuthTwoTest.php

Updated `phpunit/phpunit` to `~6.0` and `mockery/mockery` to `~1.0`
Dropped support to `PHP 5.6` and `HHVM`, as PHPUnit 6.0 [requires PHP 7.0](https://github.com/sebastianbergmann/phpunit/blob/master/composer.json#L25).

[4.0] Updated to PHPUnit 6 and Mockery 1

---

composer.json

As `illuminate/contracts:~5.4` requires at minima this PHP version.
See https://github.com/laravel/framework/blob/5.4/composer.json#L18

[3.0] Upgrade to PHP >= 5.6.4.

---

src/Two/BitbucketProvider.php

Enforce consistant use of `Arr::get()`over `array_get()`.

[3.0] Enforce consistant use of Arr::get.

---

src/One/TwitterProvider.php

This fixes an issue introduced in v3.1 where the isNewUser method was renamed in https://github.com/laravel/socialite/commit/eeb666a5ca0dac7fa5a59b67841bc203fcd5c901 to shouldBypassCache, but it was not changed in the TwitterProvider (discovered in https://stackoverflow.com/q/51865672/899126).

[3.1] Changed isNewUser call to shouldBypassCache

---

src/Two/GoogleProvider.php

In the previous version the developer needed to activate the google+ api in googles dev console. (not activating it results in 
```Client error: `GET https://www.googleapis.com/plus/v1/people/me?prettyPrint=false` resulted in a `403 Forbidden` response: {"error":{"errors":[{"domain":"usageLimits","reason":"accessNotConfigured","message":"Access Not Configured. Google+ API ```
With this api url we can get the email, name and avatar without google plus. I heard it is shutting down - so maybe this is useful.
Thanks and regards.

changed API url to not use google+, updated mapping of user object

---

src/Two/LinkedInProvider.php

LinkedIn has suddenly stopped supported the previous endpoint we used to retrieve user profile information so we need to use the new API for authenticating users.
Fixes https://github.com/laravel/socialite/issues/309

[4.0] Update LinkedIn provider

---

src/Two/GoogleProvider.php

It seems that Google's response when fetching the user info has changed.
Updated to reflect those changes. I could not find any change log on Google's side for reference.
#314 has some more info along with the specific error.
Google Returns the following for reference:
```
[
"user" => [
"id" => "",
"email" => "",
"verified_email" => "",
"name" => "",
"given_name" => "",
"family_name" => "",
"link" => "",
"picture" => "",
"locale" => ""
]
]
```

Fix mapping Google Userinfo to User Object

---

src/Two/GoogleProvider.php

Fix Google+ APIs being shutdown #317, actually just take changes from here https://github.com/laravel/socialite/pull/283

Change Google+ APIs because it will be shutdown

---

src/Two/GoogleProvider.php

I just had a Google login callback in production throw an exception because the 'name' JSON key was missing in the payload. Generally this would be a full response body:
```javascript
{
"id": "1008...",
"email": "derek...@...",
"verified_email": true,
"name": "Derek M...",
"given_name": "Derek",
"family_name": "M...",
"link": "...",
"picture": "...",
"locale": "en",
}
```
But for incomplete (or service migrated?) accounts Google may exclude some keys. I can't find complete documentation covering how this OAuth2 scope is supposed to behave. They only offer a live-fetch form: https://developers.google.com/apis-explorer/#search/userinfo/m/oauth2/v2/oauth2.userinfo.v2.me.get
Socialite's 3.0 branch already handles this field as optional: …

[4.0] Handle Google responses excluding 'name'

---

src/Two/GoogleProvider.php

This is the same patch as submitted on the `3.x` and `4.x` branches, but now is compatible back to Laravel 5.1 for those that need it, because those people do indeed exist.

[2.0] Fix Google plus API breaking change

---

src/Two/GoogleProvider.php

The correct url is https://www.googleapis.com/userinfo/v2/me

Fix Google API token url

---

src/Two/GoogleProvider.php

These updates ensure we're using the latest API urls from Google and continue to provide a working app after the shutdown of the Google+ functionality in March 2019.
By changing to the new v3 url for the user info retrieval, some of the keys from the response have changed. I've added the mappings to the old keys for the raw user data so nothing should break. These can be removed in v5.0 of Socialite.
Fixes https://github.com/laravel/socialite/issues/337

[4.0] Update Google API urls

---

src/Two/LinkedInProvider.php
tests/LinkedInProviderTest.php

In certain situations it's possible that LinkedIn doesn't returns any email addresses because they're private and not available through the API. At the moment the current provider always expects one so this change allows also to retrieve the user without expecting an email address.
Fixes https://github.com/laravel/socialite/issues/347

[4.0] Fix bug with no LinkedIn email addresses

---

src/Two/GitlabProvider.php

This makes the GitLab provider use a smaller scope by default. This has two benefits:
- If the user created the application without checking any of the scope checkboxes, GitLab will implicitly check all the boxes when submitting the form. This can result in all scopes being granted to the application, which is very broad.
- If the user created the application with only the `read_user` scope being grantable to applications, Socialite will work correctly out of the box (without requiring the user to override the scopes being requested on the Laravel side).
This closes #402.

[5.x] Only use the `read_user` scope for GitLab by default

---

.styleci.yml

Alpha ordered imports will become the default for the laravel preset in a few minutes time on styleci.io.

[3.0] Update .styleci.yml

---

src/Two/FacebookProvider.php
tests/OAuthTwoTest.php

It changes default graph version to 3.3.
Also, it introduces a way of changing the default version. I'm still having second thoughts regarding this, as it might break functionality if facebook decides to change how object is accessed, and we will need a proper mapping between graph versions. 
The usage I have in mind:
```php
return Socialite::driver('facebook')->usingGraphVersion('v5.0')->redirect();
```
Let me know what do you think

[4.x] Change default graph version, manually set desired version

---

src/SocialiteServiceProvider.php

`Illuminate\Contracts\Support\DeferrableProvider` is only available under 5.8 and above. Since we still supporting 5.7 the only option is to override the method.

[4.x] Override SocialiteServiceProvider::isDeferred() to mark as deferred.

---

tests/OAuthOneTest.php
tests/OAuthTwoTest.php

In PHPUnit 9, all ` @expectedException*` docblocks use will be soon disabled.
For now, we with PHPUnit 8, we have depreciation messages.
This PR fixes that.

Fix PHPUnit 8->9 deprectiations messages

---

tests/LinkedInProviderTest.php
tests/OAuthTwoTest.php

This PR enforces stricter assertions, using `assertSame` instead of `assertEquals`, or `assertNull` when possible.

[4.0] Enforce stricter assertions

---

src/Two/LinkedInProvider.php

There is no point filtering calling `Arr::first`, on a an array that is filtered with `Arr::where`.
---
Calling `Arr::first` is just enough.

[4.0] Remove useless Arr::where call

---

src/Two/GithubProvider.php

Github is deprecating using access_token as query parameter and they recommend sending OAuth tokens using the Authorization header.
as mentioned in this issue #427
see https://developer.github.com/v3/#oauth2-token-sent-in-a-header

[4.x] use Authorization header instead of using the `access_token` query parameter

---

src/Two/GithubProvider.php

Backport of #430 for 3.* branch.
Us with some older Laravel apps need this update to avoid issues with GitHub depreciating this in their API :D
Hoping we can release a tag `3.3.1` with this fix!

[3.x] Backport #430 - use authorization header for GitHub

---

src/SocialiteManager.php

Replaced deprecated app property in SocialiteManager

---

src/SocialiteManager.php

Removed array access on the container instance in SocialiteManger.php. The concrete class implements ArrayAccess, but the type hinted interface does not.

[4.x] Removed array access on the container instance in SocialiteManger.php

---

src/One/AbstractProvider.php
src/One/MissingTemporaryCredentialsException.php
src/One/MissingVerifierException.php
src/One/TwitterProvider.php
tests/OAuthOneTest.php

For more error controllability.
Also `Symfony\Component\Debug\Exception\FatalThrowableError` is thrown when temporary credentials are missing.
> Argument 1 passed to League\OAuth1\Client\Server\Server::getTokenCredentials() must be an instance of League\OAuth1\Client\Credentials\TemporaryCredentials, null given, called in /var/www/vendor/laravel/socialite/src/One/AbstractProvider.php on line 133

[5.x] Add custom exceptions for providers of One

---

src/Two/AbstractProvider.php

This change corrects the description of the [`buildAuthUrlFromBase()`](https://github.com/laravel/socialite/blob/4.0/src/Two/AbstractProvider.php#L165) method in [`Laravel\Socialite\Two\AbstractProvider`](https://github.com/laravel/socialite/blob/4.0/src/Two/AbstractProvider.php).
Previously, this description was duplicated with that of the [`getAuthUrl()`](https://github.com/laravel/socialite/blob/4.0/src/Two/AbstractProvider.php#L132) method.

[4.x] Changes the description of the buildAuthUrlFromBase() method

---

src/Two/AbstractProvider.php
src/Two/BitbucketProvider.php
src/Two/FacebookProvider.php
tests/OAuthTwoTest.php

There still exists a `"~5.0|~6.0"` workaround for Guzzle 6.0 replacing the `'body'` option with `'form_params'`.
1. Since Socialite 3.0 and Laravel 5.4 (2017 January 15) this package has required Composer dependency:
```
"guzzlehttp/guzzle": "~6.0",
```
* https://github.com/laravel/socialite/commit/811a7446d869dfdd9625cdfb3fa0b70207805eb2#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780
* Only the `'form_params'` key is used so the Guzzle 5 `'body'` key fallback can be removed.
2. `"guzzlehttp/guzzle"` 7.x **removes** the `GuzzleHttp\ClientInterface::VERSION` property being used to select which Guzzle option key to use.
* https://github.com/guzzle/guzzle/blob/master/UPGRADING.md#60-to-70
This removes code no longer called that will cause issues when dependencies are updated to `"guzzlehttp/guzzle": …

[4.x] Remove guzzlehttp/guzzle ~5.0 workaround

---

README.md

Shields.io works a lot better than the old pugx.org.

[5.x] Update the badges to use shields.io

---

src/Two/AbstractProvider.php
src/Two/BitbucketProvider.php
src/Two/GitlabProvider.php
src/Two/GoogleProvider.php
src/Two/LinkedInProvider.php
tests/OAuthTwoTest.php

This is a PR to close #484. This adds `grant_type=authorization_code` to the parameters in a token request, to bring it in line with the OAuth 2 spec.
I believe this should be added to the current 5.x branch, as this is somewhere between a bug fix and a backwards compatible change. Given that the majority of the socialite provider plugins have to add this parameter anyway, this will allow them to drop the override in the future but won't have any negative effects if they update to this code either.

[5.x] include grant_type=authorization code in token request parameters

---

src/Two/FacebookProvider.php

This PR is a fix to issue #487. 
According to Facebook announcement (https://developers.facebook.com/blog/post/2020/08/04/Introducing-graph-v8-marketing-api-v8), picture endpoint without `access_token` query param will not return user picture anymore by October 24, 2020.

Facebook tokenless picture endpoint fix

---

src/AbstractUser.php
src/Contracts/User.php

Hey,
```php
use Laravel\Socialite\Contracts\User as SocialiteUser;
class LoginRequest extends FormRequest
{
public function authorize()
{
return with(Socialite::driver('google')->user(), function (SocialiteUser $user) {
return $user->getRaw()['hd'] === 'myorg.com';
});
}
}
```
I can use the public method `getRaw` on `AbstractUser` to get additional information about the user like in the case of Google his organization name but when using type hinting and static analysis (shout-out to Larastan 🚀) I get an error about accessing undefined method.
Can we add getRaw to the `Socialite\Contracts\User` contract?

Add getRaw method to the User contract

---

src/Two/AbstractProvider.php
tests/OAuthTwoTest.php

This allows `$provider->user()` to be called multiple times. Handy if you want to call it in a form request to do some validation before accessing it in the controller. More info: #490.

[5.x] Cache User instance to allow $provider->user() to be called multiple times

---

src/Two/FacebookProvider.php

This reverts https://github.com/laravel/socialite/pull/489 which causes the `access_token` to be exposed to the outside when the picture url is directly served on a webpage. This can lead malicious third parties to make use of said access token and exploit it by making requests on behalf of the Facebook App. In light of this we've decided to revert these changes completely.
Since there's no way at moment anymore to do any tokenless requests to retrieve the Facebook picture only API requests with a token can be made. These need to be built by app developers themselves from now on and hidden behind a custom route in their app in order to serve the picture in a secure fashion. It's very unfortunate that Facebook made these changes but it's out of our hands unfortunately.
I've decided to …

[5.x] Revert Facebook picture access token changes

---

src/SocialiteManager.php
src/Two/GitlabProvider.php

As discussed in https://github.com/laravel/socialite/issues/509, the current Gitlab driver only supports Gitlab.com. These changes add support for self hosted instances of Gitlab.

[5.x] Added support for self hosted Gitlab instances

---

src/Two/GitlabProvider.php

This PR should fix issue #507 in a proper way than #508 
Defining scopes with Gitlab provider not working because of an incorrect URL parameter format.
In the URL, scopes should be separated by `+` which correspond to ` ` (space character) in a URL encoded format.
This problem occurred only when more than two scopes are specified.

Fix scope separator in Gitlab provider

---

src/Two/AbstractProvider.php
src/Two/GoogleProvider.php
tests/Fixtures/OAuthTwoTestProviderStub.php
tests/Fixtures/OAuthTwoWithPKCETestProviderStub.php
tests/OAuthTwoTest.php

This PR adds support for the OAuth 2.0 [PKCE](https://oauth.net/2/pkce/) extension, as discussed in #483. This extension is recommended in the latest version of the [OAuth 2.0 Security Best Current Practice](https://oauth.net/2/oauth-best-practice/). 
* Adds the PKCE logic in the core OAuth 2 provider
* Enables PKCE with Google
* Other providers can enable PKCE by setting the new `usesPKCE` property on the provider
* The default value is `false`, which is the safer way to handle backwards compatibility, even though technically OAuth providers are supposed to ignore unknown parameters so it should be theoretically possible to always send the PKCE parameters anyway

[5.x] Add support for OAuth 2.0 PKCE extension

---

src/Two/AbstractProvider.php
src/Two/GoogleProvider.php

This makes https://github.com/laravel/socialite/pull/518 opt-in since it seems to be breaking apps using the Google provider in API's.
Fixes https://github.com/laravel/socialite/issues/522

[5.x] Make PKCE opt-in

---

src/SocialiteServiceProvider.php

isDeferred method was overridden in #412 due to laravel 5.7 support and support for laravel 5.7 was dropped in the 5.0 version.

Update provider to use DeferrableProvider instead of overriding isDeferred method

---

src/Two/AbstractProvider.php
src/Two/BitbucketProvider.php
src/Two/FacebookProvider.php
src/Two/GithubProvider.php
src/Two/GitlabProvider.php
src/Two/GoogleProvider.php
src/Two/LinkedInProvider.php
tests/Fixtures/OAuthTwoTestProviderStub.php
tests/OAuthTwoTest.php

When using a SPA, you might want to redirect from your frontend.
With this change you can now get the URL for redirection like this:
```
return Socialite::driver($provider)
->stateless()
->getAuthUrl(null);
```

[6.x] Make getAuthUrl public

---

src/One/TwitterProvider.php

Hey,
I recently [made a pull request](https://github.com/thephpleague/oauth1-client/pull/138) in the [thephpleague/oauth1-client](https://github.com/thephpleague/oauth1-client) repository to handle the _scope_ for Twitter Oauth1 (with the parameter _x_auth_access_type_).
I use socialite in my app and I need to be able to set this scope manually, so I added a new method in the TwitterProvider.php to handle it.

Handle 'scope' for Twitter Oauth1

---

src/Two/GithubProvider.php

Fix github oauth authorization scope error
[docs](https://docs.github.com/en/developers/apps/building-oauth-apps/authorizing-oauth-apps#redirect-urls)

Fix github oauth authorization scope error

---

src/Contracts/Provider.php

Need this DocBlock fix so that IDEs didn't complain when we type-hint our extensions and implementations.

Fixed DocBlock return type

---

src/SocialiteManager.php
src/Two/TwitterProvider.php

Unfortunately, at the moment the endpoint for receiving email (https://developer.twitter.com/en/docs/twitter-api/v1/accounts-and-users/manage-account-settings/api-reference/get-account-verify_credentials) has not been added to the twitter v2 api.
https://developer.twitter.com/en/docs/twitter-api/migrate/twitter-api-endpoint-map
for: https://github.com/laravel/socialite/issues/570

[5.x] Add Twitter OAuth2 provider

---

src/Two/AbstractProvider.php
src/Two/User.php

It's possible for a user to grant a subset of the requested scopes.  Google has been pushing this recently...see the attached screenshot of their latest Oauth page.  Their latest default is to have no scopes checked making it quite easy for a user to select a subset of the requested scopes.
Part of the Oauth flow suggests the providers should return the approved scopes as part of the `code -> access_token` exchange if the user auth'ed a subset of the requested scopes. In my testing of Google, M365, Slack, and Zoom, the `scope` field is always returned as part of the `code -> access_token` exchange.  
There was a [recent issue ](https://github.com/laravel/socialite/issues/568) asking for this feature.
As pointed out in the link within …

add/set approvedScopes in User

---

.github/workflows/update-changelog.yml

Use the target branch of a release in the compare URL when updating the changelog through GitHub Actions.

[5.x] Use release target branch in changelog compare URL

---

src/Two/TwitterProvider.php

For Twitter apps that are considered a [confidential client](https://developer.twitter.com/en/docs/authentication/oauth-2-0/authorization-code) i.e. web apps and automated bots, a basic `Authorization` header must be passed with the `getAccessTokenResponse` request.
Failure to do so results in [authorisation failures](https://twittercommunity.com/t/trying-to-get-oauth-2-0-token-receiving-missing-valid-authorization-header-error/163633) when attempting to fetch the authenticated user.
Fortunately, Socialite doesn't need to be aware of the app type as sending the basic header doesn't seem to cause any issues with public Twitter apps, so I've just overridden the `getAccessTokenResponse` method on the `TwitterProvider` class to send the client ID and secret as basic username and password. …

Override abstract provider for Twitter's OAuth 2.0 provider

---

composer.json

Move `illuminate/contracts` from `require-dev` to `require`
cf. https://github.com/laravel/socialite/blob/5.x/src/SocialiteServiceProvider.php#L5

5.x] Move illuminate/contracts from require-dev to require

---

src/Two/AbstractProvider.php
src/Two/BitbucketProvider.php
src/Two/FacebookProvider.php
src/Two/GithubProvider.php
src/Two/GitlabProvider.php
src/Two/GoogleProvider.php
src/Two/LinkedInProvider.php
src/Two/TwitterProvider.php
tests/LinkedInProviderTest.php

This PR enforces the use `RequestOptions` constants when calling the request.
This allows to restrict the options to the only the one that really exist (have a dedicated constant).

[5.x] Use RequestOptions constants when calling the request

---

src/Two/AbstractProvider.php

This moves the currently hardcoded `getAccessTokenResponse` into their own method.  This allows children providers to construct their own headers as needed.
A perfect example of the necessity of this feature is the newer Pinterest v5 API.  In order to exchange the code for an access token, they require an `Authorization` header composed of a base64 encoded `client_id` and `client_secret`.  Without this change, the Pinterest Provider would need to entirely reimplement the `getAccessTokenResponse` method.  **With** this change, the Pinterest Provider could simply:
```php
protected function getTokenHeaders()
{
return array_merge(
parent::getTokenHeaders(),
[
'Authorization' => 'Basic ' . base64_encode("{$this->clientId}:{$this->clientSecret}"),
]
);
}
```

Add ability to override access token request headers

---

.github/workflows/tests.yml
src/AbstractUser.php

I've had to implement an attribute map on the abstract user entity to make sure dynamic property handling still worked as before.

Test on PHP 8.2

---

src/SocialiteManager.php

This PR adds the app property to the base socialite manager class to prevent PHP 8.2 warnings.
Fixes https://github.com/laravel/socialite/issues/619

[5.x] Add app property

---

src/SocialiteManager.php

Fixing the issue described here: https://github.com/laravel/socialite/issues/638
Short summary:
Octane reset SocialiteManager on each request and assign new $container object to it. However, SocialiteManager is already booted and has $this->config property, which was loaded at the very beginning from previous requests and this object stays the same and contain outdated data.

Fix: Unable to use updated config object when using Laravel Octane

---

src/SocialiteManager.php
src/Two/SlackProvider.php

This PR introduces support for a new Slack OAuth 2.0 driver. To use it, you'll need to create a new [Slack app](https://api.slack.com/apps?new_app=1).

[5.x] Add support for Slack driver

---

src/Two/SlackProvider.php

This PR changes a few things with Slack:
1. Switches to the v2 API.
2. Adds a `asBotUser()` method that switches the type of scopes requested. Slack has two kinds of tokens; `xoxb` (bot) and `xoxp` (user). When using `asBotUser()` the `user()` method will return an empty user, but a bot token will still be available.

Update Slack provider to use v2 API and allow Bot tokens

---

src/Two/SlackProvider.php
src/Two/TwitterProvider.php

This fixes an issue where phpstan throws: `Access to an undefined property Laravel\Socialite\Contracts\User::$token` on code like this:
```
$oauth_user = Socialite::driver($provider)->user();
$token = $oauth_user->token;
```
After the fix all OAuth2 drivers use the same `implements ProviderInterface` clause.

Fix phpstan issues in Twitter and Slack drivers

---

src/Two/GithubProvider.php

It has become and more common to directly identity the GitHub user via their `node_id`.
For different reasons, that would be too long to explain:
https://docs.github.com/en/graphql/guides/using-global-node-ids
I believe it would make the user object to be populated with it.

[5.x] Include GitHub `node_id` field

---

src/Two/AbstractProvider.php

This PR extracts some of the logic of the `\Laravel\Socialite\Two\AbstractProvider::user()` method into a new `\Laravel\Socialite\Two\AbstractProvider::userInstance()` method.
Nothing changes, but each provider can now override `userInstance()` and had some extra logic or retrieve additional data.
Probably one of the first use case could be for the `GitHub` provider and its new expiring tokens: the token response now comes with a new field called `refresh_token_expires_in` (possibly `null`), that will can now be attached to the user in a simple way:
```php
// in src/Two/GithubProvider.php
/**
* {@inheritdoc}
*/
function userInstance(array $response, array $user)
{
$this->user = parent::userInstance($response, $user);
$this->user->refreshTokenExpiresIn = …
```

(feat) Extract some logic to a `userInstance` method.

---

src/Two/LinkedInProvider.php

The linkedIn response replaced/removed the array key `storageSize` with `displaySize`, this change will check for both.
It currently throws an exception:
```
ErrorException GET /auth/linkedin
Undefined array key "storageSize"
```
Closes: https://github.com/laravel/socialite/issues/669

update avatar and originalAvatar display size check

---

src/Two/LinkedInProvider.php
tests/LinkedInProviderTest.php

Add vanityName on query to get the "nickname"

[5.x] Update LinkedInProvider.php

---

src/Two/AbstractProvider.php
tests/OAuthTwoTest.php

According to [RFC-6749](https://datatracker.ietf.org/doc/html/rfc6749#section-2.3.1) clients can choose from a number of authentication methods to authenticate with the authorization server.
Section 2.3.1 states that clients can put the credentials either as a Basic authorization header or passing the credentials in the body of the POST.
Right now, the default method for Socialite (in AbstractProvider) is to pass the credentials in the body of the POST.
However, the spec states this:
> Including the client credentials in the request-body using the two parameters is NOT RECOMMENDED and SHOULD be limited to clients unable
> to directly utilize the HTTP Basic authentication scheme (or other
> password-based HTTP authentication schemes).
So Socialite passes the credentials using the "non …

[5.x] Adding basic authentication by default on signed routes

---

src/Two/GoogleProvider.php
tests/Fixtures/GoogleTestProviderStub.php
tests/OAuthTwoTest.php

Fixes: #683 
---
When issuing a refreshToken call with Google - you don't get a new refresh token. You are expected to keep the original one. At the moment Socialite makes an assumption that you will - thus crashes with:
```
Laravel\Socialite\Two\Token::__construct(): Argument 2 ($refreshToken) must be of type string, null given, called in vendor/laravel/socialite/src/Two/AbstractProvider.php on line 353.
```
Overrode `refreshToken` with specific implementation on Google, then added a test.

Correct issue with Google refreshToken() method.

---

composer.json
src/Two/FacebookProvider.php

Facebook recently made changes to its Facebook Login on iOS: https://developers.facebook.com/blog/post/2024/03/28/changes-made-to-fb-login-sdk/
When a user does not allow app tracking, the login uses a new 'limited login' flow that returns an OIDC token. This token can not be used to access Facebook's Graph API. That means the current Facebook provider does not work in this 'limited login' flow. Apple requires you to use Facebook's latest SDK version.  That SDK version uses this new 'limited login' flow. This makes the current Facebook socialite provider unusable when validating a Facebook login via iOS SDK.
This PR fixes that by adding support for the OIDC token in a way that does not break or impact the regular Facebook login.
I implemented the validation of the OIDC token based on …

Support OIDC token in Facebook provider (Facebook Limited Login)

---

src/Two/GoogleProvider.php

Calling **`getUserByToken`** twice from GoogleProvider will result in obtaining null value for the second call. If you directly use `getContents()` from `GuzzleHttp\Psr7\Stream` to retrieve values, after the first retrieval, you need to execute `seek(0)` to reset the pointer position to the beginning. This is necessary for the second retrieval to work properly. `__toString()` handles this internally.
Scenario :
When using the **`GuzzleHttp\Client`** class, I've implemented a **`LogMiddleware`**. This middleware is primarily for logging the `request body` and `response body` of each API call. Consequently, during logging, `getContents` is executed once, leading to `getContents` during the return of `getUserByToken` actually receiving null.

Correct issue with GoogleProvider getUserByToken() method

---

README.md

Update the Socialite Providers URL to (https://socialiteproviders.com/) as the current link (https://socialiteproviders.netlify.com/) is not accessible.

Update Socialite Providers URL

---

src/SocialiteManager.php
src/Two/SlackOpenIdProvider.php
tests/SlackOpenIdProviderTest.php

This pull request adds a separate Slack OpenID provider. It follows the entire auth flow, documented by Slack at: https://api.slack.com/authentication/sign-in-with-slack#implementation
The name of the provider class and retrieving configuration is inspired based on the LinkedIn OpenID provider.
To try the new provider out, you have to create a Slack application with the user scopes `openid`, `profile` and `email`.
This pull request closes issue #702

[5.x] Add Slack OpenID provider

---

src/Two/AbstractProvider.php

Currently, Laravel Socialite allows custom parameters to be added to the authentication request via the with method, providing flexibility to developers for handling various OAuth providers' unique requirements. However, there is no built-in support for adding custom parameters to the access token request.
```
$parameters = ['custom_param' => 'value'];
return Socialite::driver('provider')
->with($parameters)
->stateless()
->user();
```
With this update, the with method will now ensure that the custom parameters are included in both the authentication and access token requests.
This enhancement aligns the functionality of access token requests with that of authentication requests, providing a more cohesive and powerful toolset for developers using Laravel Socialite.

Support the custom parameters of the access token request

---

src/SocialiteManager.php
src/Two/XProvider.php

X (formerly known as Twitter) currently redirects twitter.com to x.com. However, with OAuth 2.0 on X, when the authorization server redirects to twitter.com, the authorization screen still appears at twitter.com (https://twitter.com/i/oauth2/authorize). In this state, the session logged in on x.com is not shared, which may lead to authorization with a different account or require re-login.
Therefore, I have added a new OAuth 2.0 provider that redirects to x.com.
Thank you.

Add X Provider
