laravel/socialite

readme.md
Looks like it was a copy paste from laravel/cashier
=> Reworded Readme to be relevant to socialite.

src/Two/GithubProvider.php
Github didn't return email field before.
Even if $scopes has user:email entry.
Replaces #40, #41
=> Add Email To GitHub User Data

src/Two/AbstractProvider.php
Causing PHP E_NOTICE Undefined property
=> Add missing $redirectUrl property definition to AbstractProvider

src/Two/FacebookProvider.php
https://developers.facebook.com/docs/apps/changelog
=> Update Facebook API version to 2.3

src/Two/FacebookProvider.php
When login with Facebook them is no returning fields: gender and verified.
=> Facebook Login is not returning some fields

src/One/TwitterProvider.php
Add location and description missing data. Location and description always exist https://github.com/thephpleague/oauth1-client/blob/master/src/Client/Server/Twitter.php#L51
=> Add twitter location and description fields

src/Two/FacebookProvider.php
Graph [v2.5](https://developers.facebook.com/docs/apps/changelog) is out. :)
=> Update Graph version to v2.5

src/AbstractUser.php
There is currently no nice way of retrieving the raw data set by the provider. This should change that.
=> Allow retrieval of raw user data from AbstractUser

src/Two/FacebookProvider.php
Facebook just released [Graph v2.6](https://developers.facebook.com/docs/apps/changelog) today at F8. :)
=> Update Facebook Graph API version to v2.6

src/Two/AbstractProvider.php
Allows the caller to set the Client proxy, Because GFW in China
https://en.wikipedia.org/wiki/Great_Firewall
=> Allows the caller to set the Client

src/AbstractUser.php, src/One/AbstractProvider.php, src/Two/AbstractProvider.php, src/Two/InvalidStateException.php
=> Some docblocks style fixes

.travis.yml
See https://github.com/laravel/socialite/blob/2.0/composer.json#L13
=> Also tests with PHP >= 5.4

src/AbstractUser.php
=> Declare the user propserty

.gitattributes
Do not export some files and folders
=> Do not export some files and folders

readme.md
See https://github.com/laravel/socialite/pull/156#issuecomment-221674862
=> Add a note on not including state and response_type

.travis.yml
=> Also test with PHP 7

tests/OAuthOneTest.php
=> Ensure the $user property can be accessed.

tests/OAuthOneTest.php, tests/OAuthTwoTest.php
=> Use stricter assertions

composer.json, tests/Fixtures/FacebookTestProviderStub.php, tests/Fixtures/OAuthOneTestProviderStub.php, tests/Fixtures/OAuthTwoTestProviderStub.php, tests/OAuthOneTest.php, tests/OAuthTwoTest.php
=> Switch tests to PSR-4 

composer.json
=> Sort composer requirements

src/Two/AbstractProvider.php, src/Two/GithubProvider.php, src/Two/GoogleProvider.php, src/Two/LinkedInProvider.php
Prefer Arr calls instead of helpers
=> Prefer Arr calls instead of helpers

composer.json
=> Also permits phpunit ~5.0

src/Two/AbstractProvider.php
I am using the same configuration on different parts of an application and needed it to be redirected to different locations. I checked forums and it seems this feature was requested elsewhere as well:
http://stackoverflow.com/questions/30487429/laravel-5-and-socialite-new-redirect-after-login
=> Added setRedirectUrl method for dynamic URL redirection

readme.md
Add VersionEye dependencies status
=> Add VersionEye dependencies status

src/Two/FacebookProvider.php
Added "link" field to get user's facebook profile url.
=> Added "link" field to get user's facebook profile url

readme.md
I didn't realize this existed at first, so a link might be helpful for people looking to integrate with other platforms. This might also cut down on the number of PRs you get for adding new providers :)
=> Add a link to Socialite Providers

src/Two/GoogleProvider.php
Added "avatar_original" which returns a full size photo instead of 50x50 for Google provider.
=> Added full-size photo for Google provider

readme.md
=> Update docs on retrieving user via token

tests/OAuthOneTest.php, tests/OAuthTwoTest.php
=> [3.0] Remove unused variables.

phpunit.xml
=> [3.0] Tune up PHPunit.

src/Two/InvalidStateException.php
=> [3.0] Avoid FQN in code.

.travis.yml
=> [3.0] No need to suggest packages.

src/Facades/Socialite.php, src/SocialiteManager.php, src/SocialiteServiceProvider.php
=> [3.0] Use ::class notation.

composer.json
=> [3.0] Always sort require.

src/Two/FacebookProvider.php, tests/OAuthTwoTest.php
Same issue as https://github.com/laravel/socialite/pull/214 is affecting those of us on the v2 branch.
=> Fix #214 for v2.0 branch

tests/OAuthTwoTest.php
=> [3.0] Remove useless variable.

src/Two/AbstractProvider.php
Let user pass a single scope as a string.
=> [3.0] Let user pass a single scope as a string.

README.md
=> Update README.md : specify required Laravel version

src/Two/AbstractProvider.php
=> [3.0] Fix docblocks.

src/Two/FacebookProvider.php
=> Bump Graph API version to v2.10

src/SocialiteManager.php
Error given at L155 because Str is not imported.
=> Fixed missing import statement

README.md
Made it clear that this package takes advantage of package discovery.
=> Added package discovery notes to readme

src/Two/FacebookProvider.php, tests/OAuthTwoTest.php
I've just bumped FB API version.
=> Bump Graph API version to v2.11

src/One/AbstractProvider.php, src/Two/AbstractProvider.php
Fix `@return` annotations for redirect response after the changes made by the following PR https://github.com/laravel/socialite/pull/232
=> Fix PHPDoc

tests/Fixtures/FacebookTestProviderStub.php, tests/Fixtures/OAuthTwoTestProviderStub.php, tests/OAuthOneTest.php, tests/OAuthTwoTest.php
Use ::class notation in tests.
=> [3.0] Use ::class notation in tests.

src/Two/GoogleProvider.php
=> [3.0] Extract Google avatar url.

composer.json
Add `composer.json` homepage and support sections.
=> [3.0] Add composer.json homepage and support sections.

.gitattributes, .gitignore
=> [3.0] Fix .git* files.

src/Two/FacebookProvider.php
FacebookProvider : no need to set data twice
=> [3.0] FacebookProvider : no need to set data twice

src/SocialiteManager.php, src/Two/GitlabProvider.php
Originally opened in PR #129. However, as Gitlab has gain more popularity thought I might try to add it to core again. I've been running this code under my own fork for Laravel Shift for a while now.
=> Create provider for Gitlab

src/SocialiteManager.php, tests/Fixtures/FacebookTestProviderStub.php, tests/Fixtures/OAuthTwoTestProviderStub.php, tests/OAuthOneTest.php, tests/OAuthTwoTest.php
Avoid FQCN and prefer imports.
=> [3.0] Avoid FQCN and prefer imports.

tests/OAuthOneTest.php, tests/OAuthTwoTest.php
=> [3.0] Fix tearDown visibility.

tests/OAuthOneTest.php, tests/OAuthTwoTest.php
]Use modern `phpunit` TestCase namespace.
=> [3.0 ]Use modern phpunit TestCase namespace.

composer.json
Add `ext-json` as a composer requirement.
=> [4.0] Add ext-json as a composer requirement.

src/Two/GoogleProvider.php
No need to use array_add() helper.
=> [3.0] No need to use array_add() helper.

src/Facades/Socialite.php
This will improve IntelliSense support for Socialite Facade.
=> documenting magic method in Socialite facade

src/AbstractUser.php, src/One/AbstractProvider.php, src/SocialiteManager.php
This PR fixes some docs and imports the user contract.
=> [8.x] Fix docs, import contract

composer.json, src/SocialiteManager.php, tests/SocialiteManagerTest.php
Reverts https://github.com/laravel/socialite/pull/438
=> [4.x] Fix container call

composer.json
Hi,
There is no guzzle v8.0 yet 😄
=> Fix guzzle version

UPGRADE.md
=> [5.x] Update UPGRADE.md

src/SocialiteManager.php
=> Fix bitbucket

src/AbstractUser.php, src/Contracts/User.php
=> Revert "Add getRaw method to the User contract"

src/Two/AbstractProvider.php, tests/OAuthTwoTest.php
fixing the bugs in #518, see that PR for the discussion
=> fix PKCE for token request

src/Two/BitbucketProvider.php, src/Two/FacebookProvider.php, src/Two/GitlabProvider.php, src/Two/LinkedInProvider.php, tests/LinkedInProviderTest.php
…URLs.
Always prefer the `query` client argument instead of manually building the URLs
=> [5.x] Always prefer the query client argument

src/Two/AbstractProvider.php
Removed an unecessary assignment in src/Two/AbstractProvider.php
=> Removed unnecessary assignment

src/AbstractUser.php
=> Fix PHP 8.1 issues

.github/workflows/tests.yml, composer.json
Depends on https://github.com/thephpleague/oauth1-client/pull/147
=> [5.x] Throw deprecations in CI

src/SocialiteManager.php
This PR fixes a return docblock
=> [5.x] Fix a docblock

src/Two/BitbucketProvider.php, src/Two/GithubProvider.php
This PR enforces stricter comparisons
=> [5.x] Enforce stricter comparisons

tests/OAuthOneTest.php
This PR removes useless variables
=> [5.x] Remove useless variables

src/AbstractUser.php, src/Contracts/User.php
The PR fixes the return types of a few `Laravel\Socialite\Contracts\User`'s methods. It will sove false positives when using static analyzers.
=> [5.x] Fix User return types

src/SocialiteManager.php
=> Fixed identation

.gitattributes, .github/workflows/static-analysis.yml, composer.json, phpstan.neon.dist
This pull request adds type checking to this repository.
=> [5.x] Adds type checking

.github/workflows/tests.yml, composer.json, phpunit.xml.dist, tests/OAuthTwoTest.php
This pull request adds L11 support to Socialite.
=> [develop] Adds L11 support

src/Two/AbstractProvider.php, tests/OAuthTwoTest.php
This reverts commit 05af22c279ab275c38d386635379366d2349f796.
=> Revert "Adding basic authentication by default on signed routes (#684)"
